### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by RDIL** [area4lib/area4#188]
# Feature request

## Idea

Being able to cache the divider array

## Context

Right now, `util.py` scans the divider file every time the array of dividers is requested.  We should cache this.  

## Helpfulness

More speedy

## Anything Else

We should make a variable that is null, make the divider file lines go to a variable the first time, then in the future check if it is null.  If it is null, fetch the stuff.  It is not, return the cached array.

cc @N8python

**Comment by RDIL** [comment]
@N8python can you look into this please

**Comment by N8python** [comment]
I will soon.
