### ISSUE TITLE
Hacktoberfest 2019

### ISSUE THREAD

**Issue by RDIL** [area4lib/area4#195]
Hello everyone!

Area4 is now open for hacktoberfest 2019 pull requests.  Feel free to contribute anything, fix some of our starter issues, or just give the repo a star!  

See you in the pull requests tab :)

**Comment by adalbertobrant** [comment]
Hi I wanna to contribute could you give me some help? I want to contribute to dividers.txt, what I have to do?

**Comment by RDIL** [comment]
Hey @adalbertobrant!
First, find a character that hasn't been added yet, click on the edit file button, scroll to the bottom, add 12 of those characters on the blank line, and hit commit.  Next, document the new divider by editing `docs/dividers.rst` (just add a new list item at the end), and lastly, open a pull request.

Hope this helps!

**Comment by Laronk** [comment]
Hey @RDIL, could I contribute to, or is this a single person issue?

**Comment by adalbertobrant** [comment]
> docs/dividers.rst

Hello RDIL, I did not find dividers.rst, did you mean div-looks.rst?

**Comment by RDIL** [comment]
Hey sorry, yeah it’s div-looks.rst

**Comment by adalbertobrant** [comment]
> Hey sorry, yeah it’s div-looks.rst

Thanks for the opportunity to help dividers, it is a nice project.

**Comment by RDIL** [comment]
Closing for now.  See everyone next year!
