### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by RDIL** [area4lib/area4#297]
Hello everyone!

area4 is now open for Hacktoberfest 2020 pull requests!!

Feel free to contribute some dividers (see the contributing dividers section), fix some of our starter issues, or just give the repository a star to help others find it!  

See you in the pull requests tab 😄

## Contributing Dividers

Contributing dividers is simple and only requires 3 steps:
1. Add a divider to the end of `area4/dividers.txt`
2. Add an entry to the end of the list at `docs/div-looks.rst`
3. Open a pull request

**Comment by NEERAJAP2001** [comment]
@RDIL sir, I want to work on this!!

**Comment by RDIL** [comment]
Hey @NEERAJAP2001,
feel free to contribute a divider if you want!

**Comment by Mahendra7985** [comment]
i would like to work on that

**Comment by RDIL** [comment]
Hey @Mahendra7985,
feel free to contribute a divider if you want!
